name: Deploy with Ansible

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Deploy with Ansible
      run: |
        mkdir -p /home/runner/.ssh/
        touch /home/runner/.ssh/config
        touch /home/runner/.ssh/id_rsa
        echo -e "${{ secrets.ANSIBLE_SSH_KEY }}" > /home/runner/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git clone https://github.com/Adil-K123/Infra-as-code-Project-01.git /tmp/infra-repo
        git clone https://github.com/Adil-K123/Application-Project01.git /tmp/code-repo/Application-Project01
        cd /tmp/infra-repo/ansible
        ansible-playbook main.yml
